apiVersion: v1
kind: ConfigMap
metadata:
  name: python-kafka-test-config
data:
  KAFKA_HOST: my-cluster-kafka-bootstrap.strimzi.svc:9092
  KAFKA_TOPIC: python-kafka-test
  KAFKA_USERNAME: python-kafka-test-user
