apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: haproxy-cfg
    files:
      - haproxy/haproxy.cfg
      - haproxy/coraza.cfg
  - name: coraza-spoa-cfg
    files:
      - coraza-spoa/coraza-spoa.yaml

resources:
  - deployment.yaml
  - service.yaml
