apiVersion: openidclient.keycloak.crossplane.io/v1alpha2
kind: Client
metadata:
  name: onboarding-demo-app
spec:
  forProvider:
    realmIdRef:
      name: onboarding
    clientId: demo-app
    name: Demo App
    enabled: true
    accessType: PUBLIC
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    validRedirectUris:
      - "http://localhost:8080/*"
    webOrigins:
      - "+"
  providerConfigRef:
    name: keycloak-provider-config
