apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: onboarding-groupadminpermissions-group
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    name: onboarding-managed-group
    realmIdRef:
      name: onboarding
  providerConfigRef:
    name: keycloak-provider-config
---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Memberships
metadata:
  name: basic-memberships
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    groupIdRef:
      name: "onboarding-groupadminpermissions-group"
    members:
      - "alice"
    realmIdRef:
      name: "onboarding"
  providerConfigRef:
    name: "keycloak-provider-config"