apiVersion: realm.keycloak.crossplane.io/v1alpha1
kind: Realm
metadata:
  name: onboarding
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    realm: onboarding
    enabled: true
    displayName: "Onboarding Realm"
  providerConfigRef:
    name: keycloak-provider-config
