apiVersion: role.keycloak.crossplane.io/v1alpha1
kind: Role
metadata:
  name: onboarding-app-admin
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  forProvider:
    name: app-admin
    description: Full administrative access to the onboarding demo app
    realmIdRef:
      name: onboarding
  providerConfigRef:
    name: keycloak-provider-config
