apiVersion: v2
name: strimzi-cluster-operator
description: Deploys the Strimzi Kafka operator
version: 0.1.0
dependencies:
  - name: strimzi-kafka-operator
    version: 1.2.0
    repository: oci://quay.io/strimzi-helm